#issues #1 #2 email handling
FreddieMwau/Onboarding_Email_Coordinator pull request #7
Opened 2024-02-16 12:51 UTC by mbunix

Added Email handling Functionality and Error  Handler

2024-02-16 13:25 UTC, FreddieMwau requested changes
Great work on the solution 👍🏽 ,  just make the changes and we're good

2024-02-16 13:25 UTC, FreddieMwau commented on Framework/InitAllApplications.xaml
There are a few changes needed:
* Wrap all activities with a Try Catch block
* Store system & business exception emails in the Constants Tab of the Config file
* Avoid hard coding values by using variables & arguments to hold them
* Follow best practices for naming variables, i,e "str_Outlook_Account"

2024-02-19 08:18 UTC, mbunix commented on Framework/InitAllApplications.xaml
Fixed changes requested

2024-02-20 08:02 UTC, FreddieMwau commented on Framework/InitAllApplications.xaml
Push the changes & I'll review them

2024-02-20 20:48 UTC, closed without merging

2024-02-20 20:49 UTC, FreddieMwau reviewed
Changes implemented in a different branch