Issue#2 email handling
FreddieMwau/Onboarding_Email_Coordinator pull request #8
Opened 2024-02-20 09:38 UTC by mbunix

Tried to break the implementation into new Prs

2024-02-20 20:43 UTC, FreddieMwau requested changes
Good work, avoid hard coding values & handle the arguments on the System exception and we're good

2024-02-20 20:43 UTC, FreddieMwau commented on Emails/GetEmailDetails.xaml
Make the following changes 
* stop using hard coded values on Send Outlook Mail Message (Reply To) > BusinessRuleException
![image](https://github.com/FreddieMwau/Onboarding_Email_Coordinator/assets/37485156/26d7eacb-90a8-4bd7-a7d9-7c317a6bf1b4)
* Create variables to hold the arguments values in TakeScreenShot.xaml, also don't hard code values on the Send Outlook Mail Message (Reply To) this is in System Exception
![image](https://github.com/FreddieMwau/Onboarding_Email_Coordinator/assets/37485156/5ffbed85-b2cd-4bcf-b61c-88fc6c767d53)

2024-02-21 09:52 UTC, mbunix commented
Made the changes , watch the orchestrator asset folder

2024-02-21 12:34 UTC, FreddieMwau approved these changes

2024-02-21 12:35 UTC, FreddieMwau requested changes
Revert back to how you'd set up the exception emails, they need to be in the Constants Tab & not the Assets Tab

2024-02-23 13:05 UTC, FreddieMwau requested changes
Make the changes in the commented xamls

2024-02-23 13:05 UTC, FreddieMwau commented on Emails/GetEmailDetails.xaml
Add the rethrow activity in the Business Exception and this is good

2024-02-23 13:05 UTC, FreddieMwau commented on Data/Config.xlsx
Have the email body and subject save in this excel and not assets 
![image](https://github.com/FreddieMwau/Onboarding_Email_Coordinator/assets/37485156/b1febbae-67fe-4b4c-959c-cd6cff58dc5a)

2024-02-23 13:05 UTC, FreddieMwau commented on Emails/GetEmailDetails.xaml
Also change the destination where the attachment will be saved to the shared folder as you suggested

2024-02-26 09:41 UTC, FreddieMwau approved these changes

2024-02-26 09:42 UTC, merged